name: energy_dashboard
description: Mobile app for the energy-dashboard website.

version: 1.0.2
### Latest Release build: 26.10.2023
### Current Android build number: 4
### Current iOS build number: 3

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  webview_flutter: ^4.4.1
  path_provider: ^2.1.1
  webview_flutter_android: ^3.12.0
  webview_flutter_wkwebview: ^3.9.1
  flutter_spinkit: ^5.2.0
  url_launcher: ^6.1.14
  dio: ^5.3.3
  provider: ^6.0.5
  flutter_native_splash: ^2.3.4
  firebase_core: ^2.19.0
  flutter_svg: ^2.0.7
  go_router: ^12.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  get_it: ^7.6.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  reorderables: ^0.6.0
  amplify_flutter: ^1.5.0
  amplify_auth_cognito: ^1.5.0
  package_info_plus: ^4.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.6


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 19

flutter_native_splash:
  color: "#F5F5F5"
  image: "assets/app_icon.png"
  #branding: "assets/bfe_logo.png"
  android_12:
    color: "#F5F5F5"
    #branding: "assets/bfe_logo.png"


flutter:
  uses-material-design: true
  fonts:
    - family: FrutigerLT
      fonts:
        - asset: assets/fonts/FrutigerLT/FrutigerLTStd-Black.otf
        - asset: assets/fonts/FrutigerLT/FrutigerLTStd-BlackCn.otf
        - asset: assets/fonts/FrutigerLT/FrutigerLTStd-BlackItalic.otf
        - asset: assets/fonts/FrutigerLT/FrutigerLTStd-Bold.otf
        - asset: assets/fonts/FrutigerLT/FrutigerLTStd-BoldCn.otf
        - asset: assets/fonts/FrutigerLT/FrutigerLTStd-BoldItalic.otf
        - asset: assets/fonts/FrutigerLT/FrutigerLTStd-Cn.otf
        - asset: assets/fonts/FrutigerLT/FrutigerLTStd-ExtraBlackCn.otf
        - asset: assets/fonts/FrutigerLT/FrutigerLTStd-italic.otf
        - asset: assets/fonts/FrutigerLT/FrutigerLTStd-Light.otf
        - asset: assets/fonts/FrutigerLT/FrutigerLTStd-LightCn.otf
        - asset: assets/fonts/FrutigerLT/FrutigerLTStd-LightItalic.otf
        - asset: assets/fonts/FrutigerLT/FrutigerLTStd-Roman.otf
        - asset: assets/fonts/FrutigerLT/FrutigerLTStd-UltraBlack.otf
  assets:
    - assets/
    - assets/icons/
    - assets/icons/ampel_system/
    - assets/icons/app_bar/
    - assets/icons/charts/
    - assets/icons/kpi_card/
    - assets/icons/flash_message/
    - assets/icons/nav_bar/
    - assets/translations/
    - assets/translations/api/
    - assets/translations/local/
    - assets/translations/local/privacy_policy/
    - assets/translations/web/